no longer using symbols as r12 has merged the contents of symbols into the c4d object. Also tags are now returning as dictionaries instead of arrays. Not yet working, as I'm still getting "AttributeError: 'c4d.SelectionTag' object has no attribute 'GetSelection'" error, which makes no sense since the c4d.SelectionTag object contains a GetSelection method in the Python Documentation. *grumbles*